In [782]:
import pandas as pd

pd.set_option("display.max_rows", 0)
pd.set_option("display.max_columns", 0)
pd.set_option("display.width", 1000)
pd.set_option("display.float_format", "{:.6f}".format)

dataset = pd.read_csv('data/kyiv_apartments.csv')
dataset

      apartment_id  price_usd  ...  latitude  longitude
0         34086914     350000  ... 50.407906  30.555220
1         34086845      50000  ... 50.443483  30.410410
2         34082011      54000  ... 50.477227  30.436326
3         34086818      74500  ... 50.517723  30.594435
4         34086833      75000  ... 50.368288  30.453596
5         34086296     210000  ... 50.502837  30.422004
6         34086794      79999  ... 50.417885  30.632552
7         34086791     105000  ... 50.413099  30.600007
8         34086795      65000  ... 50.423171  30.672433
...            ...        ...  ...       ...        ...
1372      34246318      98000  ... 50.393295  30.470862
1373      34246317      58000  ... 50.498659  30.466984
1374      34246313      67000  ... 50.508427  30.505365
1375      34246314      87000  ... 50.391012  30.463633
1376      34246312      85500  ... 50.435595  30.598253
1377      34243398     100200  ... 50.459862  30.452796
1378      34246357     110000  ... 50.428330  30.477873
1379      34246360      56000  ... 50.418702  30.649676
1380      34242114     240000  ... 50.408264  30.635112

[1381 rows x 12 columns]

In [783]:
dataset.describe()

         apartment_id      price_usd  ...    latitude   longitude
count     1381.000000    1381.000000  ... 1381.000000 1381.000000
mean  33954720.083997  212113.957277  ...   50.442525   30.526474
std     835252.090635  333276.272524  ...    0.040762    0.075533
min   23553009.000000   23000.000000  ...   50.301055   30.331332
25%   34075314.000000   79900.000000  ...   50.411486   30.477873
50%   34083526.000000  125000.000000  ...   50.434877   30.524322
75%   34139759.000000  215000.000000  ...   50.472615   30.588963
max   34249268.000000 4000000.000000  ...   50.585417   30.705787

[8 rows x 10 columns]

In [784]:
dataset1 = dataset.drop(columns=['apartment_id', 'living_area', 'kitchen_area', 'latitude', 'longitude'])
dataset1 = dataset1.dropna()
dataset1 = dataset1.drop_duplicates()
type(dataset1)

pandas.DataFrame

In [785]:
unique_districts = sorted(dataset1['district'].unique().tolist())
unique_districts

['Академгородок',
 'Александровская Слободка',
 'Багриновая гора',
 'Батыева Гора',
 'Беличи',
 'Березняки',
 'Берковец',
 'Бортничи',
 'Борщаговка',
 'Быковня',
 'Ветряные Горы',
 'Виноградарь',
 'Воскресенка',
 'Вышгородский Массив',
 'Галаганы',
 'Голосеев',
 'Голосеевский',
 'Дарницкий',
 'Демеевка',
 'Деснянский',
 'Днепровский',
 'Жуляны',
 'Зверинец',
 'Караваевы Дачи',
 'Конча-Заспа',
 'Кудрявец',
 'Куреневка',
 'Левобережный Масив',
 'Лесной Массив',
 'Липки',
 'Лукьяновка',
 'Минский Массив',
 'Мостицкий Массив',
 'Мышеловка',
 'Нивки',
 'Никольская Борщаговка',
 'Никольская Слободка',
 'Новая Дарница',
 'Новобеличи',
 'Новое строение',
 'Оболонский',
 'Оболонь',
 'Осокорки',
 'Отрадный',
 'Паньковщина',
 'Первомайский Массив',
 'Печерск',
 'Печерский',
 'Подол',
 'Подольский',
 'Позняки',
 'Приорка',
 'Проспект Науки',
 'Радужный Массив',
 'Русановка',
 'Саперная Слободка',
 'Саперное Поле',
 'Святошино',
 'Святошинский',
 'Северно-Броварский Масив',
 'Совки',
 'Солдатская Слободка',
 'Соломенский',
 'Соломянка',
 'Соцгород',
 'Старая Дарница',
 'Старый Киев',
 'Сырец',
 'Татарка',
 'Теличка',
 'Теремки-1',
 'Теремки-2',
 'Троещина',
 'Турецкий городок',
 'Феофания',
 'Харьковский Массив',
 'Центр',
 'Черепанова гора',
 'Черная Гора',
 'Чоколовка',
 'Шевченковский',
 'Шулявка']

In [786]:
district_mapping = {
    # Голосіївський
    'Багриновая гора': 'Голосеевский',
    'Голосеев': 'Голосеевский',
    'Голосеевский': 'Голосеевский',
    'Демеевка': 'Голосеевский',
    'Конча-Заспа': 'Голосеевский',
    'Мышеловка': 'Голосеевский',
    'Новое строение': 'Голосеевский',
    'Паньковщина': 'Голосеевский',
    'Проспект Науки': 'Голосеевский',
    'Саперная Слободка': 'Голосеевский',
    'Теличка': 'Голосеевский',
    'Теремки-1': 'Голосеевский',
    'Теремки-2': 'Голосеевский',
    'Феофания': 'Голосеевский',

    # Дарницький
    'Бортничи': 'Дарницкий',
    'Дарницкий': 'Дарницкий',
    'Новая Дарница': 'Дарницкий',
    'Осокорки': 'Дарницкий',
    'Позняки': 'Дарницкий',
    'Харьковский Массив': 'Дарницкий',

    # Деснянський
    'Быковня': 'Деснянский',
    'Деснянский': 'Деснянский',
    'Лесной Массив': 'Деснянский',
    'Троещина': 'Деснянский',

    # Дніпровський
    'Березняки': 'Днепровский',
    'Воскресенка': 'Днепровский',
    'Днепровский': 'Днепровский',
    'Левобережный Масив': 'Днепровский',
    'Никольская Слободка': 'Днепровский',
    'Радужный Массив': 'Днепровский',
    'Русановка': 'Днепровский',
    'Северно-Броварский Масив': 'Днепровский',
    'Соцгород': 'Днепровский',
    'Старая Дарница': 'Днепровский',

    # Оболонський
    'Минский Массив': 'Оболонский',
    'Оболонский': 'Оболонский',
    'Оболонь': 'Оболонский',

    # Печерський
    'Зверинец': 'Печерский',
    'Липки': 'Печерский',
    'Печерск': 'Печерский',
    'Печерский': 'Печерский',
    'Саперное Поле': 'Печерский',
    'Черепанова гора': 'Печерский',
    'Черная Гора': 'Печерский',

    # Подільський
    'Ветряные Горы': 'Подольский',
    'Виноградарь': 'Подольский',
    'Вышгородский Массив': 'Подольский',
    'Куреневка': 'Подольский',
    'Мостицкий Массив': 'Подольский',
    'Подол': 'Подольский',
    'Подольский': 'Подольский',
    'Приорка': 'Подольский',

    # Святошинський
    'Академгородок': 'Святошинский',
    'Беличи': 'Святошинский',
    'Берковец': 'Святошинский',
    'Борщаговка': 'Святошинский',
    'Галаганы': 'Святошинский',
    'Никольская Борщаговка': 'Святошинский',
    'Новобеличи': 'Святошинский',
    'Святошино': 'Святошинский',
    'Святошинский': 'Святошинский',

    # Солом'янський
    'Александровская Слободка': 'Соломенский',
    'Батыева Гора': 'Соломенский',
    'Жуляны': 'Соломенский',
    'Караваевы Дачи': 'Соломенский',
    'Отрадный': 'Соломенский',
    'Первомайский Массив': 'Соломенский',
    'Совки': 'Соломенский',
    'Соломенский': 'Соломенский',
    'Соломянка': 'Соломенский',
    'Турецкий городок': 'Соломенский',
    'Чоколовка': 'Соломенский',

    # Шевченківський
    'Кудрявец': 'Шевченковский',
    'Лукьяновка': 'Шевченковский',
    'Нивки': 'Шевченковский',
    'Солдатская Слободка': 'Шевченковский',
    'Старый Киев': 'Шевченковский',
    'Сырец': 'Шевченковский',
    'Татарка': 'Шевченковский',
    'Центр': 'Шевченковский',
    'Шевченковский': 'Шевченковский',
    'Шулявка': 'Шевченковский',
}
dataset1['admin_district'] = dataset1['district'].map(district_mapping)
dataset1

      price_usd  total_area  ...            wall_type  admin_district
0        350000  162.000000  ...               кирпич       Печерский
1         50000   46.000000  ...               кирпич     Соломенский
2         54000   45.000000  ...               кирпич   Шевченковский
3         74500   74.500000  ...               кирпич      Деснянский
5        210000  124.900000  ...  монолитно-каркасный      Подольский
6         79999   50.000000  ...              монолит       Дарницкий
7        105000   37.000000  ...               кирпич       Дарницкий
8         65000   47.000000  ...               панель       Дарницкий
9         74000   68.700000  ...               панель       Дарницкий
...         ...         ...  ...                  ...             ...
1372      98000   40.000000  ...               кирпич     Соломенский
1373      58000   33.300000  ...              монолит      Оболонский
1374      67000   36.000000  ...               панель      Оболонский
1375      87000   35.600000  ...               кирпич    Голосеевский
1376      85500   61.000000  ...               кирпич     Днепровский
1377     100200   66.800000  ...               кирпич   Шевченковский
1378     110000   47.300000  ...  монолитно-каркасный     Соломенский
1379      56000   42.400000  ...               панель       Дарницкий
1380     240000  155.800000  ...  монолитно-кирпичный       Дарницкий

[958 rows x 8 columns]

In [787]:
dataset1 = dataset1[
    (dataset1['price_usd'] >= 20000) &
    (dataset1['price_usd'] <= 600000) &
    (dataset1['total_area'] >= 18) &
    (dataset1['total_area'] <= 250)
].copy()

In [788]:
#trying onehotencoder for admin_district and wall_type

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

X = dataset1.drop(columns=['price_usd', 'district'])
y = dataset1['price_usd']


X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=42)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first'), ['admin_district', 'wall_type'])], remainder='passthrough')
ct.set_output(transform="pandas")

X_train_encoded = ct.fit_transform(X_train)
X_test_encoded = ct.transform(X_test)
X_train_encoded.head()

      encoder__admin_district_Дарницкий  ...  remainder__rooms_count
369                            0.000000  ...                       4
1084                           0.000000  ...                       1
966                            0.000000  ...                       3
1337                           0.000000  ...                       3
813                            0.000000  ...                       4

[5 rows x 30 columns]

In [789]:
X_train_encoded

      encoder__admin_district_Дарницкий  ...  remainder__rooms_count
369                            0.000000  ...                       4
1084                           0.000000  ...                       1
966                            0.000000  ...                       3
1337                           0.000000  ...                       3
813                            0.000000  ...                       4
1204                           0.000000  ...                       2
37                             0.000000  ...                       2
143                            0.000000  ...                       4
11                             1.000000  ...                       3
...                                 ...  ...                     ...
998                            0.000000  ...                       3
30                             0.000000  ...                       1
1091                           1.000000  ...                       2
128                            1.000000  ...                       2
174                            0.000000  ...                       4
456                            0.000000  ...                       1
1293                           0.000000  ...                       4
701                            0.000000  ...                       2
168                            0.000000  ...                       1

[740 rows x 30 columns]

In [790]:
#trying ridge (works the same as usual Linear Regression (tested both))

from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression
import numpy as np

model = LinearRegression()
y_train_log = np.log1p(y_train)
model.fit(X_train_encoded, y_train_log)

y_pred_log = model.predict(X_test_encoded)
y_pred = np.expm1(y_pred_log)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2

0.6276399395868211

In [791]:
mae

36945.02851184235

In [792]:
comparison = pd.DataFrame({
    "Real price": y_test.values,
    "Predicted price": y_pred.astype(float),
})
comparison["Error $"] = comparison["Predicted price"] - comparison["Real price"]
comparison.head()

   Real price  Predicted price      Error $
0       60448     86965.939190 26517.939190
1      120000    132026.721483 12026.721483
2      129000    135667.231005  6667.231005
3      130000    143408.947735 13408.947735
4       81535     76861.453914 -4673.546086

In [793]:
cat_cols = ['admin_district', 'wall_type']
num_cols = ['total_area', 'floor', 'floors_count', 'rooms_count']

ct_scaled = ColumnTransformer(
    transformers=
    [('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first'), cat_cols),
    ('num', StandardScaler(), num_cols)]
)

X_train_scaled = ct_scaled.fit_transform(X_train)
X_test_scaled = ct_scaled.transform(X_test)

ridge_model = Ridge(alpha=0.8)
ridge_model.fit(X_train_scaled, y_train_log)

y_pred_ridge = np.expm1(ridge_model.predict(X_test_scaled))
r2 = r2_score(y_test, y_pred_ridge)
mae = mean_absolute_error(y_test, y_pred_ridge)

r2

0.6280610667202761

In [794]:
mae

36754.0736010209

In [795]:
#trying xgboost instead of ridge

import xgboost as xgb


xgb_model = xgb.XGBRegressor(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train_encoded, y_train_log)
y_pred_xgb = xgb_model.predict(X_test_encoded)
y_pred = np.expm1(y_pred_xgb)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2

0.7088409662246704

In [796]:
mae

31731.548828125

In [797]:
dataset2 = dataset.drop(columns=['longitude', 'latitude', 'apartment_id'])

dataset2['floor_ratio'] = dataset2['floor'] / dataset2['floors_count']

dataset2['is_first_floor'] = (dataset2['floor'] == 1).astype(int)
dataset2['is_last_floor'] = (dataset2['floor'] == 'floors_count').astype(int)

dataset2['area_per_room'] =  dataset2['total_area'] / dataset2['rooms_count']

dataset2['kitchen_ratio'] = dataset2['kitchen_area'] / dataset2['total_area']
dataset2['living_ratio'] = dataset2['living_area'] / dataset2['total_area']

dataset2 = dataset2[
    (dataset2['price_usd'] >= 20000) &
    (dataset2['price_usd'] <= 600000) &
    (dataset2['total_area'] >= 18) &
    (dataset2['total_area'] <= 250)
].copy()

dataset2 =dataset2.dropna().drop_duplicates()
dataset2

      price_usd  total_area  ...  kitchen_ratio  living_ratio
0        350000  162.000000  ...       0.246914      0.413580
1         50000   46.000000  ...       0.173913      0.652174
2         54000   45.000000  ...       0.155556      0.622222
3         74500   74.500000  ...       0.110067      0.561074
5        210000  124.900000  ...       0.096878      0.627702
12        67000   38.600000  ...       0.220207      0.463731
13       140000   82.200000  ...       0.147202      0.553528
14       140000   52.300000  ...       0.277247      0.413002
20        41000   28.000000  ...       0.142857      0.750000
...         ...         ...  ...            ...           ...
1366     195000   94.000000  ...       0.117021      0.542553
1369     132000   67.500000  ...       0.120000      0.644444
1371     100000   62.000000  ...       0.322581      0.516129
1373      58000   33.300000  ...       0.228228      0.387387
1376      85500   61.000000  ...       0.131148      0.721311
1377     100200   66.800000  ...       0.258982      0.489521
1378     110000   47.300000  ...       0.274841      0.296195
1379      56000   42.400000  ...       0.200472      0.424528
1380     240000  155.800000  ...       0.110398      0.550706

[661 rows x 15 columns]

In [798]:
#adding target encoder for all 84 districts

from sklearn.preprocessing import TargetEncoder

X = dataset2.drop(columns='price_usd')
y = dataset2['price_usd']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_train_log = np.log1p(y_train)

ct = ColumnTransformer(
    transformers=[
        ('target_enc', TargetEncoder(smooth="auto", cv=5, random_state=42), ['district']),
        ('onehot', OneHotEncoder(sparse_output=False,handle_unknown='ignore', drop='first'), ['wall_type']),
    ],
    remainder='passthrough'
)

ct.set_output(transform="pandas")

X_train_encoded = ct.fit_transform(X_train, y_train_log)
X_test_encoded = ct.transform(X_test)

xgb_model = xgb.XGBRegressor(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    reg_alpha=1.0,
    reg_lambda=0
)

xgb_model.fit(X_train_encoded, y_train_log)

y_pred_xgb_log = xgb_model.predict(X_test_encoded)
y_pred_xgb = np.expm1(y_pred_xgb_log)

r2 = r2_score(y_test, y_pred_xgb)
mae = mean_absolute_error(y_test, y_pred_xgb)
print(f"{r2},\n {mae}")

/run/media/vladyslav/01DCA3FC70492480/PyCharm/PycharmProjects/Project_AI_REGRESSION_DOMRIA/.venv/lib/python3.14/site-packages/sklearn/preprocessing/_target_encoder.py:341: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(

0.7611029744148254,
 34478.6328125

In [799]:
feature_names = X_train_encoded.columns
xgb_importances = xgb_model.feature_importances_

importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': (xgb_importances*100).round(3)
})
importance_df.sort_values(by='importance', ascending=False, inplace=True)

importance_df

                                     feature  importance
16                     remainder__total_area   37.314999
18                   remainder__kitchen_area   13.648000
0                       target_enc__district    9.212000
17                    remainder__living_area    6.448000
21                    remainder__rooms_count    5.092000
6                   onehot__wall_type_кирпич    4.060000
26                  remainder__kitchen_ratio    2.849000
20                   remainder__floors_count    2.828000
13                  onehot__wall_type_панель    2.378000
..                                       ...         ...
12      onehot__wall_type_монолітно-цегляний    0.555000
23                 remainder__is_first_floor    0.518000
8        onehot__wall_type_монолитно-блочный    0.461000
11  onehot__wall_type_монолитный железобетон    0.433000
15                   onehot__wall_type_цегла    0.396000
2              onehot__wall_type_железобетон    0.347000
14                onehot__wall_type_пеноблок    0.137000
3           onehot__wall_type_керамзитобетон    0.094000
24                  remainder__is_last_floor    0.000000

[28 rows x 2 columns]

In [800]:
#adding distance to the nearest subway station and to KHRESCHATYK into the code

from sklearn.neighbors import BallTree

dataset['floor_ratio'] = dataset['floor'] / dataset['floors_count']

dataset['is_first_floor'] = (dataset['floor'] == 1).astype(int)
dataset['is_last_floor'] = (dataset['floor'] == 'floors_count').astype(int)

dataset['area_per_room'] =  dataset['total_area'] / dataset['rooms_count']

dataset['kitchen_ratio'] = dataset['kitchen_area'] / dataset['total_area']
dataset['living_ratio'] = dataset['living_area'] / dataset['total_area']


dataset = dataset[
    (dataset['price_usd'] >= 20000) &
    (dataset['price_usd'] <= 400000) &
    (dataset['total_area'] >= 18) &
    (dataset['total_area'] <= 250)
].copy()

dataset = dataset.dropna().drop_duplicates()

metro_stations = {
    "Вокзальна": [50.4418, 30.4883],
    "Хрещатик": [50.4473, 30.5229],
    "Театральна": [50.4452, 30.5181],
    "Університет": [50.4442, 30.5058],
    "Арсенальна": [50.4444, 30.5453],
    "Печерська": [50.4269, 30.5383],
    "Олімпійська": [50.4323, 30.5161],
    "Палац Спорту": [50.4382, 30.5209],
    "Золоті Ворота": [50.4468, 30.5134],
    "Позняки": [50.3980, 30.6341],
    "Осокорки": [50.3957, 30.6159],
    "Харківська": [50.4011, 30.6528],
    "Лівобережна": [50.4518, 30.5982],
    "Дарниця": [50.4557, 30.6131],
    "Чернігівська": [50.4599, 30.6297],
    "Лісова": [50.4647, 30.6453],
    "Оболонь": [50.5015, 30.4981],
    "Мінська": [50.5124, 30.4986],
    "Героїв Дніпра": [50.5228, 30.4987],
    "Почайна": [50.4862, 30.4979],
    "Контрактова площа": [50.4654, 30.5168],
    "Поштова площа": [50.4592, 30.5253],
    "Лук'янівська": [50.4623, 30.4819],
    "Дорогожичі": [50.4736, 30.4492],
    "Сирець": [50.4764, 30.4308],
    "Шулявська": [50.4542, 30.4457],
    "Політехнічний інститут": [50.4508, 30.4665],
    "Берестейська": [50.4589, 30.4199],
    "Святошин": [50.4578, 30.3917],
    "Житомирська": [50.4561, 30.3653],
    "Академмістечко": [50.4649, 30.3551],
    "Голосіївська": [50.3975, 30.5085],
    "Васильківська": [50.3932, 30.4881],
    "Виставковий центр": [50.3828, 30.4777],
    "Іподром": [50.3765, 30.4687],
    "Теремки": [50.3671, 30.4542],
    "Либідська": [50.4139, 30.5247],
    "Деміївська": [50.4049, 30.5169],
    "Кловська": [50.4367, 30.5317],
    "Дружби Народів (Звіринецька)": [50.4184, 30.5452],
    "Видубичі": [50.4023, 30.5606],
    "Славутич": [50.3942, 30.6041],
    "Бориспільська": [50.4033, 30.6826],
    "Червоний Хутір": [50.4089, 30.6946]
}

metro_df = pd.DataFrame(metro_stations.values(), columns=['lat', 'lon'])

metro_radians = np.radians(metro_df[['lat', 'lon']])
dataset_radians = np.radians(dataset[['latitude', 'longitude']])

tree = BallTree(metro_radians, metric='haversine')

EARTH_RADIUS_KM = 6371.0
distances_rad, indices = tree.query(dataset_radians, k=1)

dataset['dist_to_subway_km'] = distances_rad.flatten() * EARTH_RADIUS_KM
dataset['log_dist_to_subway_km'] = np.log1p(dataset['dist_to_subway_km'])


def haversine_dist(lat1, lon1, lat2=50.4501, lon2=30.524):
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.sin(dlon/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))
    return 6371.0 * c

dataset['dist_to_center'] = haversine_dist(dataset['latitude'], dataset['longitude'])
dataset['log_dist_to_center'] = np.log1p(dataset['dist_to_center'])

In [801]:
dataset.drop(columns=['apartment_id', 'latitude', 'longitude'])

      price_usd  total_area  ...  dist_to_center  log_dist_to_center
0        350000  162.000000  ...        5.449098            1.863940
1         50000   46.000000  ...       10.106319            2.407514
2         54000   45.000000  ...        8.341540            2.234471
3         74500   74.500000  ...        9.774570            2.377189
5        210000  124.900000  ...       10.779613            2.466370
12        67000   38.600000  ...       12.183523            2.578968
13       140000   82.200000  ...       10.426802            2.435962
14       140000   52.300000  ...        3.999735            1.609385
15       140000   52.300000  ...        3.999735            1.609385
...         ...         ...  ...             ...                 ...
1366     195000   94.000000  ...       10.178012            2.413949
1369     132000   67.500000  ...        4.898075            1.774626
1371     100000   62.000000  ...       15.246268            2.787863
1373      58000   33.300000  ...        7.397414            2.127924
1376      85500   61.000000  ...        6.783991            2.052069
1377     100200   66.800000  ...        6.409877            2.002814
1378     110000   47.300000  ...        4.755897            1.750225
1379      56000   42.400000  ...       11.688477            2.540694
1380     240000  155.800000  ...       10.905293            2.476983

[734 rows x 19 columns]

In [812]:
X = dataset.drop(columns='price_usd')
y = dataset['price_usd']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_train_log = np.log1p(y_train)

ct = ColumnTransformer(
    transformers=[
        ('target_enc', TargetEncoder(smooth="auto", cv=5, random_state=42), ['district']),
        ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first'), ['wall_type'])
    ],
    remainder='passthrough'
)

ct.set_output(transform='pandas')

X_train_encoded = ct.fit_transform(X_train, y_train_log)
X_test_encoded = ct.transform(X_test)


xgb_model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    n_jobs=-1,
    reg_alpha=1.0,
    reg_lambda=0
)
xgb_model.fit(X_train_encoded, y_train_log)
y_pred = np.expm1(xgb_model.predict(X_test_encoded))

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print(f"r2: {r2}, \n MAE: {mae}")

/run/media/vladyslav/01DCA3FC70492480/PyCharm/PycharmProjects/Project_AI_REGRESSION_DOMRIA/.venv/lib/python3.14/site-packages/sklearn/preprocessing/_target_encoder.py:341: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(

r2: 0.8485265374183655,
 MAE: 18546.41015625

In [803]:
feature_names = X_train_encoded.columns
xgb_importances = xgb_model.feature_importances_

importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': (xgb_importances*100).round(3)
})
importance_df.sort_values(by='importance', ascending=False, inplace=True)

importance_df

                                 feature  importance
17                 remainder__total_area   26.653000
19               remainder__kitchen_area   14.986000
34         remainder__log_dist_to_center    8.571000
33             remainder__dist_to_center    7.841000
18                remainder__living_area    5.418000
22                remainder__rooms_count    4.205000
31          remainder__dist_to_subway_km    3.125000
13              onehot__wall_type_панель    2.940000
21               remainder__floors_count    2.899000
..                                   ...         ...
16               remainder__apartment_id    0.547000
1             onehot__wall_type_газоблок    0.426000
12  onehot__wall_type_монолітно-цегляний    0.388000
6               onehot__wall_type_кирпич    0.358000
3       onehot__wall_type_керамзитобетон    0.321000
26             remainder__is_first_floor    0.306000
8    onehot__wall_type_монолитно-блочный    0.149000
14            onehot__wall_type_пеноблок    0.139000
27              remainder__is_last_floor    0.000000

[35 rows x 2 columns]

In [815]:


from sklearn.model_selection import KFold, cross_val_score

kf = KFold(n_splits=10, shuffle=True, random_state=42)

cv_r2_scores = cross_val_score(
    xgb_model,
    X_train_encoded,
    y_train_log,
    cv=kf,
    scoring='r2',
    n_jobs=-1
)
print(f"r2: {cv_r2_scores}")
print(f"mean r2: {cv_r2_scores.mean()} +- {cv_r2_scores.std()}")

r2: [0.79551545 0.76979983 0.77070474 0.79528821 0.75583849 0.79100829
 0.86075457 0.84260216 0.84446371 0.85076161]
mean r2: 0.8076737073301123 +- 0.03648921932779571